/**
 * SmartLedger API
 *
 * Contact: support@smartledger.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Organization } from './organization';


export interface User { 
    id?: string;
    name?: string | null;
    email?: string | null;
    passwordHash?: string | null;
    role?: string | null;
    orgId?: string | null;
    createdAt?: string | null;
    org?: Organization;
}

